 
# This workflow is used to build the experiment and push it to github pages

name: Deploy Testing Branch
on:
  push:
# mentioning which branch should be used to build the experimnet
    branches: 
      - testing
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v2
      with:
            node-version: '12'
            check-latest: true
    - run: |
        git clone https://github.com/virtual-labs/ph3-lab-mgmt
        cd ph3-lab-mgmt
        npm install
        node exp.js
        cd ../
        git config --local user.email "admin@vlabs.ac.in"
        git config --local user.name "vleadadmin"
        git checkout --orphan gh-pages
        git reset
        git add build/* -f
        git mv build/* ./ -f
        git commit -m "https://virtual-labs.github.io/${{ github.repository }} click on the link to test your code."
    - uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.ORG_OWNER_GITHUB_TOKEN }}
        force: true
        branch: gh-pages
 # Reference : https://github.com/marketplace/actions/github-push
